### ISSUE TITLE
xRegistry - writing binary data with '00' seems to have strange effects

### ISSUE THREAD

**Issue by marcinbojko** [PowerShell/xPSDesiredStateConfiguration#301]
When we try to write data using xRegistry like in example:

```yaml
tightvncpassword:
  dsc_key: HKEY_LOCAL_MACHINE\SOFTWARE\TightVNC\Server
  dsc_valuename: Password
  dsc_hex: true
  dsc_valuedata: 00 00 00 00 00 00 00 00
  dsc_valuetype: binary
```

Setting registry values has different effect if we are going to use '00' or not.
Let's say we want to set value to: 'aabbccdd'

We'll have:

> VERBOSE: [WIN-LO53EUODSPV]:                            [[xRegistry]DirectResourceAccess] (SET) Set registry key value 'HKLM:\SOFTWARE\TightVNC\Server\ControlPassword' to 
> '(170, 187, 204, 221)' of type 'binary'

Let's change our value to: '00bbccdd'

> VERBOSE: [WIN-LO53EUODSPV]:                            [[xRegistry]DirectResourceAccess] (SET) Set registry key value 'HKLM:\SOFTWARE\TightVNC\Server\ControlPassword' to 
> '(187, 204, 221)' of type 'binary'

First '00' get's trimmed to ''.
Single '0' instead of '00' ?
Same effect.
What about line of zeroes like: '00000000'?

> VERBOSE: [WIN-LO53EUODSPV]:                            [[xRegistry]DirectResourceAccess] (SET) Set registry key value 'HKLM:\SOFTWARE\TightVNC\Server\ControlPassword' to 
> '()' of type 'binary'

Value: 'aabbcc00dd000000' - seems to be legit.

> VERBOSE: [WIN-LO53EUODSPV]:                            [[xRegistry]DirectResourceAccess] (SET) Set registry key value 'HKLM:\SOFTWARE\TightVNC\Server\ControlPassword' to 
> '(170, 187, 204, 0, 221, 0, 0, 0)' of type 'binary'
> 

Looks like we have problem if the first byte in binary is '00' or '0'
